### PR TITLE
Loading optimization

### PR DESCRIPTION
**Pull request by AlFasGD**
Not everybody has 128 GB of RAM in 2020.

### CODE REVIEW

**Comment by Altenhh** [comment]
I'd prefer if we go around a different method, what about to actually edit a level you have to create a editor class and it will decode all the object info for you, that way we save a lot more time instead of having to load every single level in the database.

**Comment by AlFasGD** [comment]
It loads the strings, which is not expensive, the decryption and object parsing is the massive operation that's causing these loading times. Also, forcing handling loading through `Editor` is bad design, because of external behavior integration.

**Comment by SMJSGaming** [comment]
just decrypt and parse only 1 thing at the time when needed

**Comment by AlFasGD** [comment]
In case it wasn't clear, this PR makes it so that the database **only retrieves the encrypted level string and parses the objects on demand through `LoadLevel`**.

**Comment by Altenhh** [comment]
so all other levels still have the encrypted string _until_ we use `LoadLevel()`?

**Comment by AlFasGD** [comment]
All levels have all their metadata loaded normally, except for `k4` which is what we call the level string, which contains the definitions for the level colors, initial properties like starting gamemode, etc., and finally the objects.

**Comment by Altenhh** [comment]
seems good to me then, sorry that i misunderstood the code

**Pull request merged**
